"""Crear modulo compras

Revision ID: 048d3afcafd1
Revises: 5664dd46e3c5
Create Date: 2026-07-28 13:11:24.992421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048d3afcafd1'
down_revision: Union[str, Sequence[str], None] = '5664dd46e3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras',
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impuesto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'CONFIRMADA', 'CANCELADA', name='estadocompra'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_numero_documento'), 'compras', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_compras_proveedor_id'), 'compras', ['proveedor_id'], unique=False)
    op.create_table('compra_detalles',
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compra_detalles_compra_id'), 'compra_detalles', ['compra_id'], unique=False)
    op.create_index(op.f('ix_compra_detalles_producto_id'), 'compra_detalles', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compra_detalles_producto_id'), table_name='compra_detalles')
    op.drop_index(op.f('ix_compra_detalles_compra_id'), table_name='compra_detalles')
    op.drop_table('compra_detalles')
    op.drop_index(op.f('ix_compras_proveedor_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_numero_documento'), table_name='compras')
    op.drop_table('compras')
    # ### end Alembic commands ###
