"""Crear modulo catalogo

Revision ID: c85ebe8125a5
Revises: fd595263de76
Create Date: 2026-07-21 05:33:15.939776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85ebe8125a5'
down_revision: Union[str, Sequence[str], None] = 'fd595263de76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_marcas_nombre')
    )
    op.create_index(op.f('ix_marcas_nombre'), 'marcas', ['nombre'], unique=False)
    op.create_table('unidades_medida',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abreviatura', name='uq_unidades_abreviatura')
    )
    op.create_index(op.f('ix_unidades_medida_abreviatura'), 'unidades_medida', ['abreviatura'], unique=False)
    op.create_index(op.f('ix_unidades_medida_nombre'), 'unidades_medida', ['nombre'], unique=False)
    op.add_column('productos', sa.Column('marca_id', sa.Integer(), nullable=False))
    op.add_column('productos', sa.Column('unidad_medida_id', sa.Integer(), nullable=False))
    op.add_column('productos', sa.Column('sku', sa.String(length=50), nullable=False))
    op.add_column('productos', sa.Column('precio_compra_actual', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('productos', sa.Column('precio_venta_actual', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index(op.f('ix_productos_marca_id'), 'productos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=False)
    op.create_index(op.f('ix_productos_unidad_medida_id'), 'productos', ['unidad_medida_id'], unique=False)
    op.create_unique_constraint('uq_productos_sku', 'productos', ['sku'])
    op.create_foreign_key(None, 'productos', 'unidades_medida', ['unidad_medida_id'], ['id'])
    op.create_foreign_key(None, 'productos', 'marcas', ['marca_id'], ['id'])
    op.drop_column('productos', 'unidad_medida')
    op.drop_column('productos', 'precio_compra')
    op.drop_column('productos', 'precio_venta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('precio_venta', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('precio_compra', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('unidad_medida', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint('uq_productos_sku', 'productos', type_='unique')
    op.drop_index(op.f('ix_productos_unidad_medida_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index(op.f('ix_productos_marca_id'), table_name='productos')
    op.drop_column('productos', 'precio_venta_actual')
    op.drop_column('productos', 'precio_compra_actual')
    op.drop_column('productos', 'sku')
    op.drop_column('productos', 'unidad_medida_id')
    op.drop_column('productos', 'marca_id')
    op.drop_index(op.f('ix_unidades_medida_nombre'), table_name='unidades_medida')
    op.drop_index(op.f('ix_unidades_medida_abreviatura'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    op.drop_index(op.f('ix_marcas_nombre'), table_name='marcas')
    op.drop_table('marcas')
    # ### end Alembic commands ###
